services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - path: .env
        required: false
      - path: .env.example
        required: true
    volumes:
      - .:/app
    networks:
      - scrapegraphai

  ollama:
    image: ollama/ollama:${OLLAMA_IMAGE_VERSION:-0.7.0}
    environment:
      OLLAMA_KEEP_ALIVE: 24h
    expose:
      - "11434"
    volumes:
      - ollama_volume:/root/.ollama
    networks:
      - scrapegraphai

networks:
  scrapegraphai:
    driver: bridge

volumes:
  ollama_volume: